blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/EPMatt/awesome-ha-blueprints/discussions?discussions_q=category%3AQ%26A
    about: Questions about anything included in this project? Open a discussion here.
