name: Documentation Issue
description: Report an issue with the project's documentation.
title: 'Docs - '
labels:
  - documentation

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feedback! 🎉

        Please keep the template as is—it helps us review issues faster.

        This template is for **documentation issues only**. For other issues, [pick a different template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). Got a question? [Start a discussion here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).
  - type: input
    attributes:
      label: Documentation URL
      description: Link to the documentation page you are opening this report for, if applicable.
  - type: input
    attributes:
      label: Blueprint name
      description: If this issue is related to a blueprint's documentation, provide the name of the related blueprint.
  - type: textarea
    attributes:
      label: Description
      description: A concise description of what the problem is.
      placeholder: e.g. Documentation for blueprint X is not properly stating requirement Y, the Z web page is not displaying correctly on mobile, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested changes
      description: A concise description of which changes you'd suggest.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Additional Details
      options:
        - label: I'd like to help improving the documentation by working on this issue.
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
