name: New blueprint proposal
description: Suggest a new blueprint to add to the collection.
title: 'Proposal - '
labels:
  - blueprint
  - new
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your contribution! 🎉

        Please keep the template as is—it helps us review your proposal faster.

        This template is for **proposing a new blueprint**. For other issues, [pick a different template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). Got a question? [Start a discussion here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of which goals the new blueprint should achieve.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Implementation
      description: If you've an idea on how this could be implemented, post here an informal description of the steps necessary for reaching the goals for this blueprint.
  - type: checkboxes
    attributes:
      label: Additional Details
      options:
        - label: I'd like to help developing this blueprint.
  - type: textarea
    attributes:
      label: Useful resources
      description: Any blueprint/automation or resource not included in this project which achieves the same/similar goal. Include links/references to them.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the new blueprint here (corner cases which should be handled, different approaches which can be considered, etc.).
