name: New blueprint proposal
description: Suggest a new blueprint to add to the collection.
title: 'Proposal - '
labels:
  - blueprint
  - new
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report here! :tada:

        Please do not delete any part of the template, since keeping the provided structure will help maintainers to process your request more rapidly.

        This template should only be used to propose a new blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of which goals the new blueprint should achieve.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Implementation
      description: If you've an idea on how this could be implemented, post here an informal description of the steps necessary for reaching the goals for this blueprint.
  - type: checkboxes
    attributes:
      label: Additional Details
      options:
        - label: I'd like to help developing this blueprint.
  - type: textarea
    attributes:
      label: Useful resources
      description: Any blueprint/automation or resource not included in this project which achieves the same/similar goal. Include links/references to them.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the new blueprint here (corner cases which should be handled, different approaches which can be considered, etc.).
