# Blueprint metadata
blueprint:
  name: Controller - IKEA E1812 TRÃ…DFRI Shortcut button
  description: |
    # Controller - IKEA E1812 TRÃ…DFRI Shortcut button

    Controller automation for executing any kind of action triggered by the provided IKEA E1812 TRÃ…DFRI Shortcut button.
    Allows to optionally loop an action on a button long press.
    The blueprint handles double button press events natively as it is supported by the controller device itself.
    Supports Zigbee2MQTT, ZHA, deCONZ.

    Automations created with this blueprint can be connected with one or more [Hooks](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/hooks) supported by this controller.
    Hooks allow to easily create controller-based automations for interacting with media players, lights, covers and more.
    See the list of [Hooks available for this controller](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1812#available-hooks) for additional details.

    ## More Info

    â„¹ï¸ Version 2025.04.12
    ðŸ“ [Changelog](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1812/#changelog)
    ðŸ“• Full documentation regarding this blueprint is available [here](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1812).

    ðŸš€ This blueprint is part of the **[Awesome HA Blueprints](https://epmatt.github.io/awesome-ha-blueprints) project**. Please consider **[leaving a star on GitHub](https://github.com/EPMatt/awesome-ha-blueprints)**! ðŸŒŸ

  source_url: https://github.com/EPMatt/awesome-ha-blueprints/blob/main/blueprints/controllers/ikea_e1812/ikea_e1812.yaml
  domain: automation
  homeassistant:
    min_version: 2024.10.0
  # Device Selector
  input:
    controller_device:
      name: (Required) (Zigbee2MQTT, ZHA, deCONZ) Controller Device
      description: The controller device to use for the automation. Choose a value only if the remote is integrated with deCONZ, ZHA, Zigbee2MQTT.
      default: ''
      selector:
        device:
          filter:
            # source: https://www.zigbee2mqtt.io/devices/E1812.html#ikea-e1812
            - integration: mqtt
              manufacturer: IKEA
              model: TRADFRI shortcut button
            # For backwards compatability with z2m 1.x. model_id is added to end of model rather than a seperate attribute in z2m 2.x
            - integration: mqtt
              manufacturer: IKEA
              model: TRADFRI shortcut button (E1812)
            # source: https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/ikea/shortcutbtn.py
            - integration: zha
              manufacturer: IKEA of Sweden
              model: TRADFRI SHORTCUT Button
            # source: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices
            - integration: deconz
              manufacturer: IKEA of Sweden
              model: TRADFRI SHORTCUT Button
          multiple: false
    # inputs for custom actions
    action_button_short:
      name: (Optional) Button short press
      description: Action to run on short button press.
      default: []
      selector:
        action:
    action_button_long:
      name: (Optional) Button long press
      description: Action to run on long button press.
      default: []
      selector:
        action:
    action_button_release:
      name: (Optional) Button release
      description: Action to run on button release after long press.
      default: []
      selector:
        action:
    action_button_double:
      name: (Optional) Button double press
      description: Action to run on double button press.
      default: []
      selector:
        action:
    # inputs for looping custom actions on long button press events until the corresponding release event is received
    long_press_options_section:
      name: Long Press options
      icon: mdi:remote
      collapsed: true
      input:
        button_long_loop:
          name: (Optional) Button long press - loop until release
          description: Loop the button action until the button is released.
          default: false
          selector:
            boolean:
        button_long_max_loop_repeats:
          name: (Optional) Button long press - Maximum loop repeats
          description: >-
            Maximum number of repeats for the custom action, when looping is enabled.
            Use it as a safety limit to prevent an endless loop in case the corresponding stop event is not received.
          default: 20
          selector:
            number:
              min: 1.0
              max: 1000.0
              mode: slider
              step: 1.0
        helper_long_press_delay:
          name: (Optional) Helper - Long Press delay
          description: Max delay between the pushing and releasing of a button long press event. Increase this value if you notice that the long press action is not triggered properly.
          default: 250
          selector:
            number:
              min: 100.0
              max: 5000.0
              unit_of_measurement: milliseconds
              mode: box
              step: 10.0
#
# Automation schema
variables:
  # Controller ID
  controller_id: !input controller_device
  # integration id used to select items in the action mapping
  # integration type is set from trigger.id
  integration_id: '{{ trigger.id.split("-")[0] }}'
  # convert input tags to variables, to be used in templates
  button_long_loop: !input button_long_loop
  button_long_max_loop_repeats: !input button_long_max_loop_repeats
  helper_long_press_delay: !input helper_long_press_delay
  # mapping between actions and integrations
  actions_mapping:
    z2m:
      # source: https://www.zigbee2mqtt.io/devices/E1812.html#ikea-e1812
      button_short: ['on']
      button_long: [brightness_move_up]
      button_release: [brightness_stop]
      button_double: ['off']
    zha:
      # source: https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/ikea/shortcutbtn.py
      button_short: ['on']
      button_long: [move_with_on_off_0_83]
      button_release: [stop]
      button_double: ['off']
    dcz:
      # source: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices
      button_short: ['1002']
      button_long: ['1001']
      button_release: ['1003']
      button_double: ['1004']
  # pre-choose actions for buttons based on configured integration
  # no need to perform this task at automation runtime
  button_short: '{{ actions_mapping[integration_id]["button_short"] }}'
  button_long: '{{ actions_mapping[integration_id]["button_long"] }}'
  button_release: '{{ actions_mapping[integration_id]["button_release"] }}'
  button_double: '{{ actions_mapping[integration_id]["button_double"] }}'
#
# Mode Block
mode: single
max_exceeded: silent
#
# Triggers Block
triggers:
  # triggers for zigbee2mqtt
  - trigger: device
    id: z2m-button-short
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: 'on'
  - trigger: device
    id: z2m-button-long
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_move_up
  - trigger: device
    id: z2m-button-release
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_stop
  - trigger: device
    id: z2m-button-double
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: 'off'
  # triggers for ZHA
  - trigger: event
    id: zha-button-short
    event_type: zha_event
    event_data:
      device_id: !input controller_device
      command: 'on'
      endpoint_id: 1
      cluster_id: 6
  - trigger: event
    id: zha-button-long
    event_type: zha_event
    event_data:
      device_id: !input controller_device
      command: move
      endpoint_id: 1
      cluster_id: 8
  - trigger: event
    id: zha-button-release
    event_type: zha_event
    event_data:
      device_id: !input controller_device
      command: stop
      endpoint_id: 1
      cluster_id: 8
  - trigger: event
    id: zha-button-double
    event_type: zha_event
    event_data:
      device_id: !input controller_device
      command: 'off'
      endpoint_id: 1
      cluster_id: 6
  # triggers for deCONZ
  - trigger: event
    id: dcz-button-short
    event_type: deconz_event
    event_data:
      device_id: !input controller_device
      event: '1002'
  - trigger: event
    id: dcz-button-long
    event_type: deconz_event
    event_data:
      device_id: !input controller_device
      event: '1001'
  - trigger: event
    id: dcz-button-release
    event_type: deconz_event
    event_data:
      device_id: !input controller_device
      event: '1003'
  - trigger: event
    id: dcz-button-double
    event_type: deconz_event
    event_data:
      device_id: !input controller_device
      event: '1004'
#
# Conditions Block
conditions:
  - condition: and
    conditions:
      # check that the button event is not empty
      - >-
        {%- set trigger_action -%}
        {%- if integration_id == "z2m" -%}
        {{ trigger.payload }}
        {%- elif integration_id == "zha" -%}
        {{ trigger.event.data.command }}{{"_" if trigger.event.data.args|length > 0}}{{ trigger.event.data.args|join("_") }}
        {%- elif integration_id == "dcz" -%}
        {{ trigger.event.data.event }}
        {%- endif -%}
        {%- endset -%}
        {{ trigger_action not in ["","None","unknown"] }}
#
# Actions Block
actions:
  #
  # choose the sequence to run based on the received button event
  - choose:
      #
      # Actions for Button single press
      - conditions:
          - condition: trigger
            id:
              - z2m-button-short
              - zha-button-short
              - dcz-button-short
        sequence:
          # fire the ahb hook event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_short
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_short
      #
      # Actions for Button Long Press
      - conditions:
          - condition: trigger
            id:
              - z2m-button-long
              - zha-button-long
              - dcz-button-long
        sequence:
          # fire the ahb event only once, the ahb hook will take care of looping
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_long
          # run the custom action only once before entering repeat
          - choose:
              - conditions: []
                sequence: !input action_button_long
          # handle custom action looping if looping is enabled
          - choose:
              - conditions: '{{ button_long_loop }}'
                sequence:
                  # Repeat the Long Press Actions for the set number of loops
                  - repeat:
                      count: !input button_long_max_loop_repeats
                      sequence:
                        - parallel:
                            - sequence: !input action_button_long
                            - sequence:
                                - choose:
                                    - conditions: []
                                      sequence:
                                        # Wait for z2m/zha/dcz triggers for Button Long Press Release to stop looping
                                        - wait_for_trigger:
                                            # z2m triggers
                                            - trigger: device
                                              domain: mqtt
                                              device_id: !input controller_device
                                              type: action
                                              subtype: stop
                                            # zha triggers
                                            - trigger: event
                                              event_type: zha_event
                                              event_data:
                                                device_id: !input controller_device
                                                command: stop
                                                endpoint_id: 1
                                                cluster_id: 8
                                            # dcz triggers
                                            - trigger: event
                                              event_type: deconz_event
                                              event_data:
                                                device_id: !input controller_device
                                                event: '1003'
                                          timeout:
                                            milliseconds: !input helper_long_press_delay
                                          continue_on_timeout: true
                                        # If a Button Long Release is triggered wait.trigger.idx will be defined stop the loop before long_max_loop_repeats
                                        - if:
                                            - condition: template
                                              value_template: '{{ wait.trigger.idx is defined }}'
                                          then:
                                            # fire the event
                                            - event: ahb_controller_event
                                              event_data:
                                                controller: '{{ controller_id }}'
                                                action: button_release
                                            # run the custom action
                                            - choose:
                                                - conditions: []
                                                  sequence: !input action_button_release
                                            # Stop the repeat loop
                                            - stop: button_released
      #
      # Actions for Button Release Press
      - conditions:
          - condition: trigger
            id:
              - z2m-button-release
              - zha-button-release
              - dcz-button-release
        sequence:
          # fire the event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_release
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_release
      #
      # Actions for Button Double Press
      - conditions:
          - condition: trigger
            id:
              - z2m-button-double
              - zha-button-double
              - dcz-button-double
        sequence:
          # fire the event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_double
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_double
