# Blueprint metadata
blueprint:
  name: Hook - Light
  description: |
    Hook automation which allows to control a light. Supports brightness and color control both for white temperature and rgb lights. Features may vary depending on the selected Controller.

    An automation created with this blueprint must be linked to a [Controller](https://epmatt.github.io/awesome-ha-blueprints/blueprints/controllers) automation.
    Controllers are blueprints which allow to easily integrate a wide range of controllers (wall switches, remotes, dimmers, etc.) and use them to run a set of actions when interacting with them.
    They expose an abstract interface used by Hooks to create controller-based automations.

    Full documentation and a list of Controllers supported by this Hook are available [here](https://epmatt.github.io/awesome-ha-blueprints/blueprints/hooks/light).
  domain: automation
  input:
    controller_device:
      name: Controller Device
      description: The controller device which will control the light. Choose a value only if the integration used to connect the controller to Home Assistant exposes it as a Device. This value should match the one specified in the corresponding Controller automation.
      default: ''
      selector:
        device:
    controller_entity:
      name: Controller Entity
      description: The controller entity which will control the light. Choose a value only if the integration used to connect the controller to Home Assistant exposes it as an Entity. This value should match the one specified in the corresponding Controller automation.
      default: ''
      selector:
        entity:
          domain: sensor
    controller_model:
      name: Controller model
      description: The model for the controller used in this automation.
      selector:
        select:
          options:
            - IKEA E1524/E1810 5-Button remote
            - IKEA E1743 On/Off Switch & Dimmer
            - IKEA E1744 SYMFONISK rotary remote
            - IKEA E1812 Shortcut button
            - IKEA ICTC-G-1 TRADFRI wireless dimmer
            - Philips Hue Dimmer switch
    light:
      name: Light
      description: Light which will be controlled with this automation.
      selector:
        entity:
          domain: light
    light_color_mode:
      name: (Optional) Light color mode
      description: Specify how the controller will set the light color. Choose "Color Temperature" and "Hue - Saturation" depending on the features supported by your light. If you are not sure you can select "Auto".
      default: Auto
      selector:
        select:
          options:
            - Auto
            - Color Temperature
            - Hue - Saturation
    light_transition:
      name: (Optional) Light Transition
      description: Number that represents the time (in milliseconds) the light should take turn on or off, if the light supports it. This will only work when the "Force brightness at turn on" option is enabled. (When using this option on light.turn_on HA will turn on the light at minimum brightness.)
      default: 250
      selector:
        number:
          min: 0
          max: 60000
          step: 1
          unit_of_measurement: milliseconds
          mode: box
    min_brightness:
      name: (Optional) Light minimum brightness
      description: The minimum brightness the light can be set with this automation.
      default: 0
      selector:
        number:
          min: 0
          max: 255
          step: 1
          unit_of_measurement: brightness
          mode: slider
    max_brightness:
      name: (Optional) Light maximum brightness
      description: The maximum brightness the light can be set with this automation.
      default: 255
      selector:
        number:
          min: 0
          max: 255
          step: 1
          unit_of_measurement: brightness
          mode: slider
    brightness_steps_short:
      name: (Optional) Light brightness steps - short actions
      description: Number of steps from min to max brightness when controlling brightness with short actions (eg. button press).
      default: 10
      selector:
        number:
          min: 1
          max: 255
          step: 1
          unit_of_measurement: steps
          mode: box
    brightness_steps_long:
      name: (Optional) Light brightness steps - long actions
      description: Number of steps from min to max brightness when controlling brightness with long actions (eg. button hold or controller rotation).
      default: 10
      selector:
        number:
          min: 1
          max: 255
          step: 1
          unit_of_measurement: steps
          mode: box
    force_brightness:
      name: Force brightness value at turn on
      description: Force brightness to the "On brightness" input value, when the light is being turned on.
      default: false
      selector:
        boolean:
    on_brightness:
      name: On brightness
      description: Brightness value to force when turning on the light
      default: 1
      selector:
        number:
          min: 0
          max: 255
          step: 1
          unit_of_measurement: brightness
          mode: slider

# Automation schema
variables:
  # convert blueprint inputs into variables to be used in templates
  controller_model: !input controller_model
  light_color_mode: !input light_color_mode
  light: !input light
  light_transition: !input light_transition
  min_brightness: !input min_brightness
  max_brightness: !input max_brightness
  brightness_steps_short: !input brightness_steps_short
  brightness_steps_long: !input brightness_steps_long
  force_brightness: !input force_brightness
  on_brightness: !input on_brightness
  # Blueprint data
  supported_color_modes:
    Auto: auto
    Color Temperature: color_temp
    Hue - Saturation: hs_color
  supported_controllers:
    IKEA E1524/E1810 5-Button remote: ikea_e1524_e1810
    IKEA E1743 On/Off Switch & Dimmer: ikea_e1743
    IKEA E1744 SYMFONISK rotary remote: ikea_e1744
    IKEA E1812 Shortcut button: ikea_e1812
    IKEA ICTC-G-1 TRADFRI wireless dimmer: ikea_ictc_g_1
    Philips Hue Dimmer switch: philips_324131092621
  controller_mapping:
    ikea_e1524_e1810:
      brightness_up: button_up_short
      brightness_up_repeat: button_up_long
      brightness_down: button_down_short
      brightness_down_repeat: button_down_long
      color_up: button_right_short
      color_up_repeat: button_right_long
      color_down: button_left_short
      color_down_repeat: button_left_long
      toggle: button_center_short
    ikea_e1743:
      turn_on: button_up_short
      turn_off: button_down_short
      brightness_up_repeat: button_up_long
      brightness_down_repeat: button_down_long
      color_up: button_up_double
      color_down: button_down_double
    ikea_e1744:
      toggle: click_short
      brightness_up_repeat: rotate_right
      brightness_down_repeat: rotate_left
      color_up: click_double
      color_down: click_triple
    ikea_e1812:
      toggle: button_short
      color_up: button_double
    ikea_ictc_g_1:
      brightness_up_repeat: rotate_right
      brightness_down_repeat: rotate_left
    philips_324131092621:
      turn_on: button_on_short
      turn_off: button_off_short
      brightness_up: button_up_short
      brightness_up_repeat: button_up_long
      brightness_down: button_down_short
      brightness_down_repeat: button_down_long
      color_up_repeat: button_on_long
      color_down_repeat: button_off_long
  # extract controller ids
  controller_id: '{{ controller_entity if controller_device == "" else controller_device }}'
  controller_model_id: '{{ supported_controllers[controller_model] }}'
  # pre-choose actions for buttons based on configured controller
  # no need to perform this task at automation runtime
  brightness_up: '{{controller_mapping[controller_model_id]["brightness_up"]}}'
  brightness_up_repeat: '{{controller_mapping[controller_model_id]["brightness_up_repeat"]}}'
  brightness_down: '{{controller_mapping[controller_model_id]["brightness_down"]}}'
  brightness_down_repeat: '{{controller_mapping[controller_model_id]["brightness_down_repeat"]}}'
  color_up: '{{controller_mapping[controller_model_id]["color_up"]}}'
  color_up_repeat: '{{controller_mapping[controller_model_id]["color_up_repeat"]}}'
  color_down: '{{controller_mapping[controller_model_id]["color_down"]}}'
  color_down_repeat: '{{controller_mapping[controller_model_id]["color_down_repeat"]}}'
  toggle: '{{controller_mapping[controller_model_id]["toggle"]}}'
  turn_on: '{{controller_mapping[controller_model_id]["turn_on"]}}'
  turn_off: '{{controller_mapping[controller_model_id]["turn_off"]}}'
  # extract light color mode id
  light_color_mode_id: >-
    {% if light_color_mode == "Auto" %}
    {{ supported_color_modes["Hue - Saturation"] if state_attr(light, "hs_color") != None else supported_color_modes["Color Temperature"] }}
    {% else %}
    {{ supported_color_modes[light_color_mode] }}
    {% endif %}
  step_short: '{{ (max_brightness-min_brightness)/brightness_steps_short }}'
  step_long: '{{ (max_brightness-min_brightness)/brightness_steps_long }}'

# mode restart ensures long actions are interrupted when the release action is received
mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: ahb_controller_event
    event_data:
      controller: !input controller_device
  - platform: event
    event_type: ahb_controller_event
    event_data:
      controller: !input controller_entity
condition:
action:
  - variables:
      action: '{{ trigger.event.data.action }}'
  - choose:
      - conditions: '{{ action == toggle }}'
        sequence:
          - choose:
              - conditions: '{{ force_brightness }}'
                sequence:
                  - service: light.toggle
                    entity_id: !input light
                    data:
                      brightness: !input on_brightness
                      transition: '{{ light_transition / 1000 }}'
            default:
              - service: light.toggle
                entity_id: !input light
      - conditions: '{{ action == turn_on }}'
        sequence:
          - choose:
              - conditions: '{{ force_brightness }}'
                sequence:
                  - service: light.turn_on
                    entity_id: !input light
                    data:
                      brightness: !input on_brightness
                      transition: '{{ light_transition / 1000 }}'
            default:
              - service: light.turn_on
                entity_id: !input light
      - conditions: '{{ action == turn_off }}'
        sequence:
          - service: light.turn_off
            entity_id: !input light
            data:
              transition: '{{ light_transition / 1000 }}'
      - conditions: '{{ action == brightness_up }}'
        sequence:
          - service: light.turn_on
            data:
              brightness: '{{ [ [state_attr(light,"brightness")+step_short, min_brightness] | max, max_brightness] | min }}'
              transition: 0.25
              entity_id: !input light
      - conditions: '{{ action == brightness_down }}'
        sequence:
          - service: light.turn_on
            data:
              brightness: '{{ [ [state_attr(light,"brightness")-step_short, min_brightness] | max, max_brightness] | min }}'
              transition: 0.25
              entity_id: !input light
      - conditions: '{{ action == brightness_up_repeat }}'
        sequence:
          - repeat:
              while: '{{ true }}'
              sequence:
                - service: light.turn_on
                  data:
                    brightness: '{{ [ [state_attr(light,"brightness")+step_long, min_brightness] | max, max_brightness] | min }}'
                    transition: 0.25
                    entity_id: !input light
                - delay:
                    milliseconds: 250
      - conditions: '{{ action == brightness_down_repeat }}'
        sequence:
          - repeat:
              while: '{{ true }}'
              sequence:
                - service: light.turn_on
                  data:
                    brightness: '{{ [ [state_attr(light,"brightness")-step_long, min_brightness] | max, max_brightness] | min }}'
                    transition: 0.25
                    entity_id: !input light
                - delay:
                    milliseconds: 250
      - conditions: '{{ action == color_up }}'
        sequence:
          choose:
            - conditions: '{{ light_color_mode_id == "color_temp" }}'
              sequence:
                - service: light.turn_on
                  data:
                    color_temp: '{{ state_attr(light,"color_temp")|int + 50 }}'
                    transition: 0.25
                  entity_id: !input light
            - conditions: '{{ light_color_mode_id == "hs_color" }}'
              sequence:
                - service: light.turn_on
                  data:
                    hs_color: '{{ [((state_attr(light,"hs_color")[0] or 0) + 15) % 360, 100] }}'
                    transition: 0.25
                  entity_id: !input light
      - conditions: '{{ action == color_down }}'
        sequence:
          choose:
            - conditions: '{{ light_color_mode_id == "color_temp" }}'
              sequence:
                - service: light.turn_on
                  data:
                    color_temp: '{{ [state_attr(light,"color_temp")|int - 50, 1]|max }}'
                    transition: 0.25
                  entity_id: !input light
            - conditions: '{{ light_color_mode_id == "hs_color" }}'
              sequence:
                - service: light.turn_on
                  data:
                    hs_color: '{{ [((state_attr(light,"hs_color")[0] or 0) - 15) % 360, 100] }}'
                    transition: 0.25
                  entity_id: !input light
      - conditions: '{{ action == color_up_repeat }}'
        sequence:
          choose:
            - conditions: '{{ light_color_mode_id == "color_temp" }}'
              sequence:
                - repeat:
                    while: '{{ true }}'
                    sequence:
                      - service: light.turn_on
                        data:
                          color_temp: '{{ state_attr(light,"color_temp")|int + 50 }}'
                          transition: 0.25
                        entity_id: !input light
                      - delay:
                          milliseconds: 250
            - conditions: '{{ light_color_mode_id == "hs_color" }}'
              sequence:
                - repeat:
                    while: '{{ true }}'
                    sequence:
                      - service: light.turn_on
                        data:
                          hs_color: '{{ [((state_attr(light,"hs_color")[0] or 0) + 15) % 360, 100] }}'
                          transition: 0.25
                        entity_id: !input light
                      - delay:
                          milliseconds: 250
      - conditions: '{{ action == color_down_repeat }}'
        sequence:
          choose:
            - conditions: '{{ light_color_mode_id == "color_temp" }}'
              sequence:
                - repeat:
                    while: '{{ true }}'
                    sequence:
                      - service: light.turn_on
                        data:
                          color_temp: '{{ [state_attr(light,"color_temp")|int - 50, 1]|max }}'
                          transition: 0.25
                        entity_id: !input light
                      - delay:
                          milliseconds: 250
            - conditions: '{{ light_color_mode_id == "hs_color" }}'
              sequence:
                - repeat:
                    while: '{{ true }}'
                    sequence:
                      - service: light.turn_on
                        data:
                          hs_color: '{{ [((state_attr(light,"hs_color")[0] or 0) - 15) % 360, 100] }}'
                          transition: 0.25
                        entity_id: !input light
                      - delay:
                          milliseconds: 250
