# Blueprint metadata
blueprint:
  name: Example Automation Blueprint
  description: |
    A description for the blueprint

    Version: yyyy.mm.dd
  source_url: https://github.com/EPMatt/awesome-ha-blueprints/blob/main/blueprints/automation/_example/_example.yaml
  domain: automation
  input:
    example_input_boolean:
      name: Example Input Boolean
      description: A description for the example input
      # make sure only entities from the input_boolean domain can be assigned to this input
      selector:
        entity:
          domain: input_boolean
    example_text:
      name: (Optional) Example Text
      description: A description for the example input
      # wherever possible provide a default value for your inputs
      default: Sample Text Message
      # we want the user to provide a line of text, so we can skip the selector here
      # this is the only situation which doesn't require a proper input selector
    example_device:
      name: (MQTT Integration) Example Input Device
      description: A device input which demonstrates how to document an input with a specific requirement. As a bare example, this input is required only if using the MQTT Integration.
      # wherever possible provide a default value for your inputs
      default: ''
      # make sure only devices can be assigned to this input
      selector:
        device:

# Automation schema
mode: restart

trigger:
  platform: state
  entity_id: !input example_input_boolean
  from: 'off'
  to: 'on'
condition: []
action:
  # if part of your automations are comaplicated, remember to add comments to better explain what's happening
  service: persistent_notification.create
  data:
    title: This is a title
    message: !input example_text
