# Blueprint metadata
blueprint:
  name: Controller - Xiaomi WXCJKG11LM Aqara Opple 2 button remote
  description: |
    # Controller - Xiaomi WXCJKG11LM Aqara Opple 2 button remote

    Controller automation for executing any kind of action triggered by the provided Xiaomi WXCJKG11LM Aqara Opple 2 button remote. Allows to optionally loop an action on a button long press.
    Supports deCONZ, ZHA, Zigbee2MQTT.

    Automations created with this blueprint can be connected with one or more [Hooks](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/hooks) supported by this controller.
    Hooks allow to easily create controller-based automations for interacting with media players, lights, covers and more.
    See the list of [Hooks available for this controller](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/xiaomi_wxcjkg11lm#available-hooks) for additional details.

    ## More Info

    ℹ️ Version 2025.02.13
    📝 [Changelog](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/xiaomi_wxcjkg11lm/#changelog)
    📕 Full documentation regarding this blueprint is available [here](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/xiaomi_wxcjkg11lm).

    🚀 This blueprint is part of the **[Awesome HA Blueprints](https://epmatt.github.io/awesome-ha-blueprints) project**. Please consider **[leaving a star on GitHub](https://github.com/EPMatt/awesome-ha-blueprints)**! 🌟

  source_url: https://github.com/EPMatt/awesome-ha-blueprints/blob/main/blueprints/controllers/xiaomi_wxcjkg11lm/xiaomi_wxcjkg11lm.yaml
  domain: automation
  homeassistant:
    min_version: 2024.10.0
  input:
    integration:
      name: (Required) Integration
      description: Integration used for connecting the remote with Home Assistant. Select one of the available values.
      selector:
        select:
          options:
            - deCONZ
            - ZHA
            - Zigbee2MQTT
    controller_device:
      name: (deCONZ, ZHA, Zigbee2MQTT Required) Controller Device
      description: The controller device to use for the automation. Choose a value only if the remote is integrated with deCONZ, ZHA, Zigbee2MQTT.
      default: ''
      selector:
        device:
          filter:
            # source: https://www.zigbee2mqtt.io/devices/WXCJKG11LM.html#aqara-wxcjkg11lm
            - integration: mqtt
              manufacturer: Aqara
              model: Opple wireless switch (single band)
            # For backwards compatability with z2m 1.x. model_id is added to end of model rather than a seperate attribute in z2m 2.x
            - integration: mqtt
              manufacturer: Aqara
              model: Opple wireless switch (single band) (WXCJKG11LM)
            # source: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices
            - integration: zha
            # **TBConfirmed** manufacturer: Xiaomi
            # **TBConfirmed**  model: Aqara Opple 2-gang
            - integration: deconz
            # **TBConfirmed** manufacturer: Xiaomi
            # **TBConfirmed** model: Aqara Opple 2-gang
          multiple: false
    helper_last_controller_event:
      name: (Required) Helper - Last Controller Event
      description: Input Text used to store the last event fired by the controller. You will need to manually create a text input entity for this, please read the blueprint Additional Notes for more info.
      default: ''
      selector:
        entity:
          domain: input_text
    # inputs for custom actions
    action_button_1_short:
      name: (Optional) Button 1 short press
      description: Action to run on short button 1 press.
      default: []
      selector:
        action:
    action_button_1_long:
      name: (Optional) Button 1 long press
      description: Action to run on long button 1 press.
      default: []
      selector:
        action:
    action_button_1_release:
      name: (Optional) Button 1 release
      description: Action to run on button 1 release after long press.
      default: []
      selector:
        action:
    action_button_1_double:
      name: (Optional) Button 1 double press
      description: Action to run on double button 1 press.
      default: []
      selector:
        action:
    action_button_1_triple:
      name: (Optional) Button 1 triple press
      description: Action to run on triple button 1 press.
      default: []
      selector:
        action:
    action_button_2_short:
      name: (Optional) Button 2 short press
      description: Action to run on short button 2 press.
      default: []
      selector:
        action:
    action_button_2_long:
      name: (Optional) Button 2 long press
      description: Action to run on long button 2 press.
      default: []
      selector:
        action:
    action_button_2_release:
      name: (Optional) Button 2 release
      description: Action to run on button 2 release after long press.
      default: []
      selector:
        action:
    action_button_2_double:
      name: (Optional) Button 2 double press
      description: Action to run on double button 2 press.
      default: []
      selector:
        action:
    action_button_2_triple:
      name: (Optional) Button 2 triple press
      description: Action to run on triple button 2 press.
      default: []
      selector:
        action:
    # inputs for looping custom actions on long button press events until the corresponding release event is received
    button_1_long_loop:
      name: (Optional) Button 1 long press - loop until release
      description: Loop the button 1 action until the button is released.
      default: false
      selector:
        boolean:
    button_1_long_max_loop_repeats:
      name: (Optional) Button 1 long press - Maximum loop repeats
      description: >-
        Maximum number of repeats for the custom action, when looping is enabled.
        Use it as a safety limit to prevent an endless loop in case the corresponding stop event is not received.
      default: 500
      selector:
        number:
          min: 1
          max: 5000
          mode: slider
          step: 1
    button_2_long_loop:
      name: (Optional) Button 2 long press - loop until release
      description: Loop the button 2 action until the button is released.
      default: false
      selector:
        boolean:
    button_2_long_max_loop_repeats:
      name: (Optional) Button 2 long press - Maximum loop repeats
      description: >-
        Maximum number of repeats for the custom action, when looping is enabled.
        Use it as a safety limit to prevent an endless loop in case the corresponding stop event is not received.
      default: 500
      selector:
        number:
          min: 1
          max: 5000
          mode: slider
          step: 1
    # helpers used to properly recognize the remote button events
    helper_debounce_delay:
      name: (Optional) Helper - Debounce delay
      description:
        Delay used for debouncing RAW controller events, by default set to 0. A value of 0 disables the debouncing feature. Increase this value if you notice custom actions or linked Hooks running multiple times when interacting with the device. When the controller needs to be debounced,
        usually a value of 100 is enough to remove all duplicate events.
      default: 0
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: milliseconds
          mode: box
          step: 10
# Automation schema
variables:
  # convert input tags to variables, to be used in templates
  integration: !input integration
  button_1_long_loop: !input button_1_long_loop
  button_1_long_max_loop_repeats: !input button_1_long_max_loop_repeats
  button_2_long_loop: !input button_2_long_loop
  button_2_long_max_loop_repeats: !input button_2_long_max_loop_repeats
  helper_last_controller_event: !input helper_last_controller_event
  helper_debounce_delay: !input helper_debounce_delay
  # integration id used to select items in the action mapping
  integration_id: '{{ integration | lower }}'
  # mapping between actions and integrations
  actions_mapping:
    deconz:
      button_1_short: ['1002']
      button_1_long: ['1001']
      button_1_release: ['1003']
      button_1_double: ['1004']
      button_1_triple: ['1005']
      button_2_short: ['2002']
      button_2_long: ['2001']
      button_2_release: ['2003']
      button_2_double: ['2004']
      button_2_triple: ['2005']
    zha:
      button_1_short: [1_single]
      button_1_long: [1_long press]
      button_1_release: [1_release]
      button_1_double: [1_double]
      button_1_triple: [1_triple]
      button_2_short: [2_single]
      button_2_long: [2_long press]
      button_2_release: [2_release]
      button_2_double: [2_double]
      button_2_triple: [2_triple]
    zigbee2mqtt:
      # source: https://www.zigbee2mqtt.io/devices/WXCJKG11LM.html#aqara-wxcjkg11lm
      button_1_short: [button_1_single]
      button_1_long: [button_1_hold]
      button_1_release: [button_1_release]
      button_1_double: [button_1_double]
      button_1_triple: [button_1_triple]
      button_2_short: [button_2_single]
      button_2_long: [button_2_hold]
      button_2_release: [button_2_release]
      button_2_double: [button_2_double]
      button_2_triple: [button_2_triple]
  # pre-choose actions for buttons based on configured integration
  # no need to perform this task at automation runtime
  button_1_short: '{{ actions_mapping[integration_id]["button_1_short"] }}'
  button_1_long: '{{ actions_mapping[integration_id]["button_1_long"] }}'
  button_1_release: '{{ actions_mapping[integration_id]["button_1_release"] }}'
  button_1_double: '{{ actions_mapping[integration_id]["button_1_double"] }}'
  button_1_triple: '{{ actions_mapping[integration_id]["button_1_triple"] }}'
  button_2_short: '{{ actions_mapping[integration_id]["button_2_short"] }}'
  button_2_long: '{{ actions_mapping[integration_id]["button_2_long"] }}'
  button_2_release: '{{ actions_mapping[integration_id]["button_2_release"] }}'
  button_2_double: '{{ actions_mapping[integration_id]["button_2_double"] }}'
  button_2_triple: '{{ actions_mapping[integration_id]["button_2_triple"] }}'
  # build data to send within a controller event
  controller_id: !input controller_device
mode: restart
max_exceeded: silent
triggers:
  # triggers for zigbee2mqtt mqtt device action
  - trigger: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: button_1_single
  - trigger: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: button_1_hold
  - trigger: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: button_1_release
  - trigger: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: button_1_double
  - trigger: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: button_1_triple
  - trigger: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: button_2_single
  - trigger: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: button_2_hold
  - trigger: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: button_2_release
  - trigger: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: button_2_double
  - trigger: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: button_2_triple
  # triggers for other integrations
  - trigger: event
    event_type:
      - deconz_event
      - zha_event
    event_data:
      device_id: !input controller_device
conditions:
  - condition: and
    conditions:
      # check that the button event is not empty
      - >-
        {%- set trigger_action -%}
        {%- if integration_id == "zigbee2mqtt" -%}
        {{ trigger.payload }}
        {%- elif integration_id == "deconz" -%}
        {{ trigger.event.data.event }}
        {%- elif integration_id == "zha" -%}
        {{ trigger.event.data.command }}
        {%- endif -%}
        {%- endset -%}
        {{ trigger_action not in ["","None"] }}
actions:
  # debouncing - when automation is triggered multiple times, the last automation run is the one which completes execution, due to mode restart
  # therefore previous runs must wait for the debounce delay before executing any other action
  # if the delay expires and the automation is still running it means it's the last run and execution can continue
  - delay:
      milliseconds: !input helper_debounce_delay
  # extract button event from the trigger
  # provide a single string value to check against
  - variables:
      trigger_action: >-
        {%- if integration_id == "zigbee2mqtt" -%}
        {{ trigger.payload }}
        {%- elif integration_id == "deconz" -%}
        {{ trigger.event.data.event }}
        {%- elif integration_id == "zha" -%}
        {{ trigger.event.data.command }}
        {%- endif -%}
      trigger_delta: '{{ (as_timestamp(now()) - ((states(helper_last_controller_event) | from_json).t if helper_last_controller_event is not none and (states(helper_last_controller_event) | regex_match("^\{((\"a\": \".*\"|\"t\": \d+\.\d+)(, )?){2}\}$")) else as_timestamp("1970-01-01 00:00:00"))) * 1000 }}'
  # update helper
  - action: input_text.set_value
    data:
      entity_id: !input helper_last_controller_event
      value: '{{ {"a":trigger_action,"t":as_timestamp(now())} | to_json }}'
  # choose the sequence to run based on the received button event
  - choose:
      - conditions: '{{ trigger_action | string in button_1_short }}'
        sequence:
          # fire the event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_1_short
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_1_short
      - conditions: '{{ trigger_action | string in button_1_long }}'
        sequence:
          # fire the event only once before looping the action
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_1_long
          - choose:
              # if looping is enabled, loop the action for a finite number of iterations
              - conditions: '{{ button_1_long_loop }}'
                sequence:
                  - repeat:
                      while: '{{ repeat.index < button_1_long_max_loop_repeats | int }}'
                      sequence: !input action_button_1_long
            # if looping is not enabled run the custom action only once
            default: !input action_button_1_long
      - conditions: '{{ trigger_action | string in button_1_release }}'
        sequence:
          # fire the event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_1_release
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_1_release
      - conditions: '{{ trigger_action | string in button_1_double }}'
        sequence:
          # fire the event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_1_double
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_1_double
      - conditions: '{{ trigger_action | string in button_1_triple }}'
        sequence:
          # fire the event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_1_triple
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_1_triple
      - conditions: '{{ trigger_action | string in button_2_short }}'
        sequence:
          # fire the event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_2_short
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_2_short
      - conditions: '{{ trigger_action | string in button_2_long }}'
        sequence:
          # fire the event only once before looping the action
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_2_long
          - choose:
              # if looping is enabled, loop the action for a finite number of iterations
              - conditions: '{{ button_2_long_loop }}'
                sequence:
                  - repeat:
                      while: '{{ repeat.index < button_2_long_max_loop_repeats | int }}'
                      sequence: !input action_button_2_long
            # if looping is not enabled run the custom action only once
            default: !input action_button_2_long
      - conditions: '{{ trigger_action | string in button_2_release }}'
        sequence:
          # fire the event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_2_release
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_2_release
      - conditions: '{{ trigger_action | string in button_2_double }}'
        sequence:
          # fire the event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_2_double
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_2_double
      - conditions: '{{ trigger_action | string in button_2_triple }}'
        sequence:
          # fire the event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_2_triple
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_2_triple
