# yamllint disable rule:document-start
# yamllint disable rule:line-length
# Automatically locks old closed issues and PRs which did not receive any update recently
# Take care also of removing any relevant label from threads before locking them
name: 'Thread Locker'

'on':
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          # 30 days of inactivity both for closed issues and PRs
          issue-inactive-days: 30
          pr-inactive-days: 30
          issue-lock-reason: ''
          issue-comment: |
            Hi there,

            🔒 This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new ticket for related bugs.

            Thanks!
          pr-lock-reason: ''
          pr-comment: |
            Hi there,

            🔒 This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs. If you want to submit a contribution to the project, you can open a new PR.

            Thanks!
